version: '2'
services:
  store_-app:
    image: store_
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:mysql://store_-mysql:3306/store_?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
      - SPRING_DATA_JEST_URI=http://store_-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://store_-elasticsearch:9200
    ports:
      - 8080:8080
  store_-mysql:
    extends:
      file: mysql.yml
      service: store_-mysql
  store_-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: store_-elasticsearch
